name: ngx-ui-scroll ci

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      cause:
        description: 'Reason'
        required: true
        default: 'Manual triggering'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Dispatched?
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "This is dispatched"
          echo "Build reason: ${{ github.event.inputs.cause }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm run ci:lib
      - run: npm run build:lib
      - run: npm run ci:demo
      - run: npm run build:demo
      - run: npm run ci:tests
      - run: npm test

      - uses: actions/upload-artifact@v4
        with:
          name: demo-dist
          path: dist/demo

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Set env BRANCH
        run: echo "BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)" >> $GITHUB_ENV

      - name: Set env NEED
        run: |
          if [[ $BRANCH == 'master' && $GITHUB_EVENT_NAME == 'push' ]]; then
              echo "NEED=true" >> "$GITHUB_ENV"
          else
              echo "NEED=false" >> "$GITHUB_ENV"
          fi

      - name: Skip Deploy?
        if: env.NEED != 'true'
        run: echo "Only pushing to 'master' causes automatic deployment"

      - name: Checkout
        if: env.NEED == 'true'
        uses: actions/checkout@v4

      - name: Download dist
        if: env.NEED == 'true'
        uses: actions/download-artifact@v4
        with:
          name: demo-dist
          path: dist-demo-app

      - name: Deploy
        if: env.NEED == 'true'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist-demo-app